apiVersion: v1
kind: Secret
metadata:
  name: fintech-secrets
  namespace: fintech
type: Opaque
stringData:
  postgres-password: "CHANGE_IN_PROD"
  redis-password: "CHANGE_IN_PROD"
  jwt-secret: "CHANGE_IN_PROD_USE_32_CHARS_MIN"
  grafana-admin-password: "CHANGE_IN_PROD"
  binance-api-key: "REPLACE_WITH_REAL_KEY"
  binance-api-secret: "REPLACE_WITH_REAL_KEY"
  coinbase-api-key: "REPLACE_WITH_REAL_KEY"