apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
        - name: data-ingestion
          image: fintech/data-ingestion-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          envFrom:
            - configMapRef:
                name: fintech-config
            - secretRef:
                name: fintech-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10